# Generated by Django 6.0.7 on 2026-07-31 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('does_conduct_inquests', models.BooleanField(default=False)),
                ('name_for_inquest', models.CharField(blank=True, max_length=250)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.jurisdiction')),
            ],
        ),
    ]
