[project]
name = "backend-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Michael Eden", email = "michael.eden100@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.7",
    "djangorestframework>=3.17.1",
    "psycopg2>=2.9.13",
]

[project.scripts]
backend-django = "backend_django:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
