# Generated by Django 6.0.7 on 2026-07-29 18:51

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=5000)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('quotes', models.CharField(blank=True, max_length=5000)),
                ('key_case_reason', models.CharField(blank=True, max_length=255)),
                ('is_judicial_review', models.BooleanField()),
                ('authority_citations', models.ManyToManyField(blank=True, related_name='authority_cited_by', to='authorities.authority')),
                ('authority_related', models.ManyToManyField(blank=True, related_name='authority_related_by', to='authorities.authority')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorities', to='common.jurisdiction')),
                ('groups', models.ManyToManyField(blank=True, related_name='authorities', to='authorities.authoritygroup')),
            ],
            options={
                'verbose_name_plural': 'authorities',
            },
        ),
        migrations.CreateModel(
            name='AuthorityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CASE_LAW', 'Case Law'), ('REFERENCE', 'Reference'), ('COMMISSION_REPORT', 'Commission Report'), ('STATUTE', 'Statute'), ('MEDIA', 'Media'), ('SUMMARY', 'Summary')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='authorities.authority')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='AuthorityKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('INQUEST', 'Inquest'), ('FACTOR', 'Factor'), ('EVIDENCE', 'Evidence')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('synonyms', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='authority_keyword_unique_lower_name_category')],
            },
        ),
        migrations.AddField(
            model_name='authority',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='authorities', to='authorities.authoritykeyword'),
        ),
    ]
