# Generated by Django 6.0.7 on 2026-07-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('EQUITY', 'Equity'), ('FACTOR', 'Factor'), ('HEALTH', 'Health'), ('INMATE', 'Inmate'), ('POLICE', 'Police'), ('WORKPLACE', 'Workplace')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('synonyms', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=5000)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('quotes', models.CharField(blank=True, max_length=5000)),
                ('key_case_reason', models.CharField(blank=True, max_length=255)),
                ('is_judicial_review', models.BooleanField()),
                ('authority_citations', models.ManyToManyField(blank=True, related_name='authority_cited_by', to='authorities.authority')),
                ('authority_related', models.ManyToManyField(blank=True, related_name='authority_related_by', to='authorities.authority')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorities', to='common.jurisdiction')),
                ('keywords', models.ManyToManyField(blank=True, related_name='authorities', to='authorities.authoritykeyword')),
            ],
            options={
                'verbose_name_plural': 'authorities',
            },
        ),
        migrations.CreateModel(
            name='AuthorityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='authorities.authority')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
