# Generated by Django 6.0.7 on 2026-07-31 00:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('rank', models.SmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
            },
        ),
        migrations.CreateModel(
            name='AuthorityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='authority_group_unique_lower_name')],
            },
        ),
        migrations.CreateModel(
            name='AuthorityKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(choices=[('INQUEST', 'Inquest'), ('FACTOR', 'Factor'), ('EVIDENCE', 'Evidence')], max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('synonyms', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='authority_keyword_unique_lower_name_category')],
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('overview', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=5000)),
                ('notes', models.CharField(blank=True, max_length=5000)),
                ('quotes', models.CharField(blank=True, max_length=5000)),
                ('key_case_reason', models.CharField(blank=True, max_length=250)),
                ('is_judicial_review', models.BooleanField()),
                ('citations', models.ManyToManyField(blank=True, related_name='cited_by', to='authorities.authority')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorities', to='common.jurisdiction')),
                ('groups', models.ManyToManyField(blank=True, related_name='authorities', to='authorities.authoritygroup')),
                ('keywords', models.ManyToManyField(blank=True, related_name='authorities', to='authorities.authoritykeyword')),
            ],
            options={
                'verbose_name_plural': 'authorities',
            },
        ),
        migrations.CreateModel(
            name='AuthorityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('document_type', models.CharField(choices=[('CASE_LAW', 'Case Law'), ('REFERENCE', 'Reference'), ('COMMISSION_REPORT', 'Commission Report'), ('STATUTE', 'Statute'), ('MEDIA', 'Media'), ('SUMMARY', 'Summary')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=500)),
                ('citation', models.CharField(blank=True, max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='authorities.authority')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_documents', to='common.jurisdiction')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='authorities.authoritylevel')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
