# Generated by Django 6.0.7 on 2026-07-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authoritygroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
