name: inquests

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app.Dockerfile
    depends_on:
      - db
    volumes:
      - ../app/:/usr/src/app/
      - ../data/:/usr/src/data/
    env_file: .env.dev
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:15.4
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file: .env.dev
    ports:
      - "5432:5432"

volumes:
  db_data:
