# Generated by Django 6.0.7 on 2026-07-31 00:08

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseOfDeath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'causes of death',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('also_known_as', models.CharField(blank=True, max_length=250)),
                ('notes', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'parties',
            },
        ),
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Inquest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('overview', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=15000)),
                ('key_case_reason', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('recommendation_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_to_recommendations', models.CharField(blank=True, max_length=5000)),
                ('sitting_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('import_metadata', models.CharField(blank=True, null=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquests', to='common.jurisdiction')),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unspecified/Undetermined')], max_length=50)),
                ('manner', models.CharField(choices=[('ACCIDENT', 'Accident'), ('NATURAL', 'Natural'), ('SUICIDE', 'Suicide'), ('HOMICIDE', 'Homicide'), ('UNDETERMINED', 'Undetermined'), ('PENDING', 'Pending'), ('OTHER', 'Other')], max_length=50)),
                ('reason_for_inquest', models.CharField(blank=True, choices=[('PSYCHIATRIC_RESTRAINT', 'Psychiatric Restraint'), ('CUSTODY_INMATE', 'Custody-Inmate'), ('CUSTODY_POLICE', 'Custody-Police'), ('CONSTRUCTION', 'Construction'), ('MINING', 'Mining'), ('CHILD_CYFSA', 'Child (CYFSA)'), ('DISCRETIONARY', 'Discretionary inquest'), ('PENDING', 'Pending inquest')], max_length=50, null=True)),
                ('cause_description', models.CharField(blank=True, max_length=500)),
                ('inmate_type', models.CharField(blank=True, choices=[('FEDERAL', 'Federal'), ('PROVINCIAL_REMAND', 'Provincial - On Remand'), ('PROVINCIAL_SENTENCED', 'Provincial - Serving Sentence'), ('PROVINCIAL_IMMIGRATION', 'Provincial - Immigration Detention')], max_length=50, null=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inquests.causeofdeath')),
                ('inquest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deceased', to='inquests.inquest')),
            ],
            options={
                'verbose_name_plural': 'deceased',
            },
        ),
        migrations.CreateModel(
            name='InquestDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('document_type', models.CharField(choices=[('VERDICT_AND_EXPLANATION', 'Verdict & Explanation'), ('RESPONSE_TO_RECOMMENDATIONS', 'Response to Recommendations'), ('STANDING_RULING', 'Standing Ruling'), ('SCOPE', 'Scope'), ('MEDIA', 'Media')], max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=500)),
                ('inquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inquests.inquest')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='InquestGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='inquest_group_unique_lower_name')],
            },
        ),
        migrations.AddField(
            model_name='inquest',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='inquests', to='inquests.inquestgroup'),
        ),
        migrations.CreateModel(
            name='InquestKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(choices=[('EQUITY', 'Equity'), ('FACTOR', 'Factor'), ('HEALTH', 'Health'), ('INMATE', 'Inmate'), ('POLICE', 'Police'), ('WORKPLACE', 'Workplace')], max_length=250)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('synonyms', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='inquest_keyword_unique_lower_name_category')],
            },
        ),
        migrations.AddField(
            model_name='inquest',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='inquests', to='inquests.inquestkeyword'),
        ),
        migrations.AddField(
            model_name='inquest',
            name='presiding_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inquests', to='inquests.participant'),
        ),
        migrations.AddField(
            model_name='inquest',
            name='recommendation_recipients',
            field=models.ManyToManyField(blank=True, related_name='inquests', to='inquests.party'),
        ),
        migrations.AddField(
            model_name='party',
            name='party_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party', to='inquests.partytype'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(choices=[('POI', 'Presiding Officer'), ('INQUEST_COUNSEL', 'Inquest Counsel'), ('PARTY_COUNSEL', 'Party Counsel'), ('POLICE', 'Police'), ('PROGRAM_ADMINISTRATOR', 'Program Administrator'), ('SUPPORT', 'Support'), ('OTHER', 'Other')], max_length=50)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('category'), name='role_unique_lower_name_category')],
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='participants', to='inquests.role'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('party_type'), name='party_unique_lower_name_party_type'),
        ),
    ]
