# Generated by Django 6.0.7 on 2026-07-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseOfDeath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'causes of death',
            },
        ),
        migrations.CreateModel(
            name='InquestKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('INQUEST', 'Inquest'), ('FACTOR', 'Factor'), ('EVIDENCE', 'Evidence')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('synonyms', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='PresidingOfficer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inquest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('overview', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=5000)),
                ('key_case_reason', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('import_metadata', models.CharField(blank=True, null=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquests', to='common.jurisdiction')),
                ('keywords', models.ManyToManyField(blank=True, related_name='inquests', to='inquests.inquestkeyword')),
                ('presiding_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquests', to='inquests.presidingofficer')),
            ],
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=50)),
                ('manner', models.CharField(choices=[('ACCIDENT', 'Accident'), ('NATURAL', 'Natural'), ('SUICIDE', 'Suicide'), ('HOMICIDE', 'Homicide'), ('UNDETERMINED', 'Undetermined'), ('PENDING', 'Pending'), ('OTHER', 'Other')], max_length=50)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inquests.causeofdeath')),
                ('inquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased', to='inquests.inquest')),
            ],
            options={
                'verbose_name_plural': 'deceased',
            },
        ),
        migrations.CreateModel(
            name='InquestDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('inquest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inquests.inquest')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.CreateModel(
            name='RecommendationRecipient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inquests', models.ManyToManyField(blank=True, to='inquests.inquest')),
            ],
        ),
    ]
