# Generated by Django 6.0.7 on 2026-07-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquest',
            old_name='parties',
            new_name='recommendation_recipients',
        ),
    ]
